apiVersion: v1
kind: Service
metadata: 
  name: email-app
spec:
  type: LoadBalancer
  ports: 
  - port: 8090
    targetPort: 8090
  selector: 
    app: email-app

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: email-app  
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: email-app
  template: 
    metadata: 
      labels: 
        app: email-app
    spec: 
      containers: 
      - name: email-app
        image: mycontainer.azurecr.io/email:latest         
        ports: 
        - containerPort: 8090